### PR TITLE
Update what-is-solid.md

### PR DESCRIPTION
**Pull request by Mitzi-Laszlo**

### CODE REVIEW

**Comment by kjetilk** [comment]
Hmmm, I think we need to have different explanations geared towards different audiences here. Also, different audiences will look at different sites, e.g. some will look at the Solid project site, some will look at github, some will look at Inrupt's site, etc. They could carry different parts of the message.

**Comment by Mitzi-Laszlo** [comment]
@RubenVerborgh @justinwb maybe you could connect with @pjworrall and @danwilkinsoncreative as the [Explaining the Vision Panel](https://github.com/solid/culture/blob/master/panels.md#explaining-the-vision-panel) and work on this so that it's ready for editorial review once the editors are approved?

**Comment by danwilkinsoncreative** [comment]
@kjetilk I think the intent for this was to find a simple, universal way of expressing what Solid so there can't be any confusion or misinterpretation. A description that anyone could understand and appreciate. It could of course become more detailed/elaborate for audiences who already have a greater understanding but the ultimate aim would be to ensure clarity across the board.

**Comment by danwilkinsoncreative** [comment]
@RubenVerborgh @justinwb do we have a description elsewhere that you feel more accurately describes Solid?

**Comment by RubenVerborgh** [comment]
We all had a take on this somewhere in an issue; @Mitzi-Laszlo likely knows where that one is.

**Comment by kjetilk** [comment]
@danwilkinsoncreative right, but you could argue that the question of what Solid is can be answered with "Solid is a simple addition of identity, data model and access control to the current Web", but with that answer, most people would go "huh?" :-) So, at some point, we have to go into the ramifications of that simple statement, and I think that the proposed text goes to far (and thus has insufficient), but just saying "will enable separation of data and apps" doesn't go far enough.

It is not easy to say what Solid is, because though technologically simple, its ramifications may be huge. Therefore, I'm not sure that the description that appeals to everyone can be found.

**Comment by RubenVerborgh** [comment]
I don't think that enough input from https://github.com/solid/information/issues/180 (which is the thread I was looking for above) has been incorporated.

If it were me, I'd (not surprisingly) start from what I wrote there, but of course other people have relevant input too.

Comparing for instance

> Solid is a catalyst to create initiatives for building a fair web. 

to

> Solid is an open ecosystem of people, data, and services.

and

> Solid aims to empower people and foster innovation by freeing data from silos.

we see a possibility to make things more concrete.

For instance:

> Solid is an ecosystem of technologies that fosters innovation and empowers people by offering precise control over data across application and organization boundaries.

**Comment by pjworrall** [comment]
I suggested we needed a methodology to make sure everyone's perspective is reflected and makes it possible to iterate together over the message.

First step I believe is to separate concerns. The "Vision, mission and values" and "What is Solid" are related but independent. I suggest starting with the first and then "backing out" iteratively to more detail. Then you will arrive at what Solid is in the context of the "Vision, mission and values".

We must decide what the audience is as well. Starting with "Vision, mission and values" should enable everyone to focus on a **general** audience and then evolve the message to different audiences as you break out across other propositions.

I started some content in the @solid/explaining-the-vision-panel . Wouldn't it be easier to have this discussion there instead of an issue?

**Comment by Mitzi-Laszlo** [comment]
Hi [Explaining the Vision Panel](https://github.com/solid/culture/blob/master/panels.md#explaining-the-vision-panel), there are many conversations related to this panel that are listed on the [panel.md](https://github.com/solid/culture/blob/master/panels.md#explaining-the-vision-panel) and you have been reaching out to me independently. What I'll do is close the issues and pull requests, leave them listed in panel.md for reference and start a single email conversation with all of you involved so you can coordinate between yourself to submit a final proposal for editorial review.

**Pull request closed without merging**
